# Content Based filtering

In [1]:
import numpy as np

In [2]:
genres = ["Action", "Adventure", "Sci-Fi", "Romance", "Drama"]

In [3]:
movie_features = {
    "Movie1": [1, 0, 1, 0, 0],  # Action, Sci-Fi
    "Movie2": [0, 1, 1, 0, 0],  # Adventure, Sci-Fi
    "Movie3": [0, 0, 0, 1, 1],  # Romance, Drama
    "Movie4": [1, 1, 0, 0, 0],  # Action, Adventure
    "Movie5": [0, 0, 1, 0, 1]   # Sci-Fi, Drama
}

In [4]:
liked_movies = ['Movie1', 'Movie2']

In [7]:
user_profile = np.zeros(len(genres), dtype=int)
user_profile

array([0, 0, 0, 0, 0])

In [8]:
for movie in liked_movies:
  user_profile += movie_features[movie]

In [9]:
user_profile

array([1, 1, 2, 0, 0])

In [10]:
sims = {}
for movie, feats in movie_features.items():
  if movie in liked_movies:
    continue
  sim = np.dot(user_profile, feats)
  sims[movie] = sim
  print(f'similarity between {movie} and user profile is {sim}')

similarity between Movie3 and user profile is 0
similarity between Movie4 and user profile is 2
similarity between Movie5 and user profile is 2


In [12]:
recommend = sorted(sims.items(), key=lambda x: x[1], reverse=True)

In [13]:
recommend

[('Movie4', np.int64(2)), ('Movie5', np.int64(2)), ('Movie3', np.int64(0))]

# Collaborative filtering

In [14]:
feedback = np.array([
    [1, 1, 0, 0],  # User1
    [1, 1, 1, 1],  # User2
    [1, 0, 1, 0],  # User3
    [0, 1, 0, 1],  # User4
    [0, 0, 0, 1]   # User5
], dtype=int)

In [18]:
target_user = 0
user_vectors = feedback
target_vector = user_vectors[target_user]

In [19]:
user_vectors

array([[1, 1, 0, 0],
       [1, 1, 1, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [0, 0, 0, 1]])

In [20]:
sims = user_vectors.dot(target_vector)

In [22]:
print("Similarity scores vs User1:", sims)


Similarity scores vs User1: [2 2 1 1 0]


In [27]:
sims[target_user] = -1
most_sim_index = np.argmax(sims)

In [28]:
items_user1_liked = set(np.where(target_vector == 1)[0])     # {0, 1} for ItemA, ItemB
items_user2_liked = set(np.where(user_vectors[most_sim_index] == 1)[0])
# Items to recommend are in User2's set but not in User1's set
recommend_items_idx = items_user2_liked - items_user1_liked
print("Recommend item indices:", recommend_items_idx)

Recommend item indices: {np.int64(2), np.int64(3)}
