<a href="https://colab.research.google.com/github/assaabriiii/My-Machine-Learning-Journey/blob/main/SMOTE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install opendatasets

In [ ]:
import opendatasets as od

In [ ]:
od.download("https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud")

Skipping, found downloaded files in "./creditcardfraud" (use force=True to force download)


In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("creditcardfraud/creditcard.csv")

In [ ]:
df

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, average_precision_score

X = df.drop('Class', axis=1)
y = df['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# گام ۳: آموزش مدل
model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train, y_train)

# گام ۴: ارزیابی
y_pred = model.predict(X_test)
print("\nگزارش طبقه‌بندی:")
print(classification_report(y_test, y_pred))

print("\nماتریس confusion:")
print(confusion_matrix(y_test, y_pred))

print("\nAverage Precision Score:")
print(average_precision_score(y_test, y_pred))


گزارش طبقه‌بندی:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.84      0.69      0.76        98

    accuracy                           1.00     56962
   macro avg       0.92      0.85      0.88     56962
weighted avg       1.00      1.00      1.00     56962


ماتریس confusion:
[[56851    13]
 [   30    68]]

Average Precision Score:
0.5830411541771329


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
from sklearn.ensemble import RandomForestClassifier


In [ ]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("\nگزارش طبقه‌بندی:")
print(classification_report(y_test, y_pred))


گزارش طبقه‌بندی:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.84      0.69      0.76        98

    accuracy                           1.00     56962
   macro avg       0.92      0.85      0.88     56962
weighted avg       1.00      1.00      1.00     56962



In [ ]:
print("\nماتریس confusion:")
print(confusion_matrix(y_test, y_pred))

print("\nAverage Precision Score:")
print(average_precision_score(y_test, y_pred))


ماتریس confusion:
[[56851    13]
 [   30    68]]

Average Precision Score:
0.5830411541771329


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from scipy.spatial import distance

def smote(minority_samples, N, k=5):
    T = minority_samples.shape[0]

    if N < 100:
        indices = np.random.choice(T, int(T * (N / 100)), replace=False)
        minority_samples = minority_samples[indices]
        N = 100
        T = minority_samples.shape[0]

    num_synthetic = int((N / 100) * T)
    synthetic_samples = np.zeros((num_synthetic, minority_samples.shape[1]))

    idx = 0
    for i in range(T):
        sample = minority_samples[i]

        distances = distance.cdist([sample], minority_samples)[0]
        distances[i] = np.inf

        nearest_indices = np.argsort(distances)[:k]
        nearest_neighbors = minority_samples[nearest_indices]

        num_to_generate = int(N / 100)
        for _ in range(num_to_generate):
            neighbor_idx = np.random.choice(range(k))
            neighbor = nearest_neighbors[neighbor_idx]

            diff = neighbor - sample
            gap = np.random.rand()
            synthetic = sample + gap * diff

            synthetic_samples[idx] = synthetic
            idx += 1

    return synthetic_samples


print(df.shape)
print(df['Class'].value_counts())

X = df.drop('Class', axis=1).values
y = df['Class'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

model_normal = LogisticRegression(max_iter=1000, random_state=42)
model_normal.fit(X_train, y_train)
y_pred_normal = model_normal.predict(X_test)

print(classification_report(y_test, y_pred_normal))
print(confusion_matrix(y_test, y_pred_normal))
print("ROC-AUC:", roc_auc_score(y_test, y_pred_normal))

minority_indices = np.where(y_train == 1)[0]
minority_samples = X_train[minority_indices]

synthetic_samples = smote(minority_samples, N=500, k=5)

X_train_smote = np.vstack((X_train, synthetic_samples))
y_train_smote = np.hstack((y_train, np.ones(synthetic_samples.shape[0])))

unique, counts = np.unique(y_train_smote, return_counts=True)
print(dict(zip(unique, counts)))

model_smote = LogisticRegression(max_iter=1000, random_state=42)
model_smote.fit(X_train_smote, y_train_smote)
y_pred_smote = model_smote.predict(X_test)

print(classification_report(y_test, y_pred_smote))
print(confusion_matrix(y_test, y_pred_smote))
print("ROC-AUC:", roc_auc_score(y_test, y_pred_smote))

(284807, 31)
Class
0    284315
1       492
Name: count, dtype: int64


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.84      0.69      0.76        98

    accuracy                           1.00     56962
   macro avg       0.92      0.85      0.88     56962
weighted avg       1.00      1.00      1.00     56962

[[56851    13]
 [   30    68]]
ROC-AUC: 0.8468244676880319
{np.float64(0.0): np.int64(227451), np.float64(1.0): np.int64(2364)}
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.71      0.84      0.77        98

    accuracy                           1.00     56962
   macro avg       0.86      0.92      0.88     56962
weighted avg       1.00      1.00      1.00     56962

[[56831    33]
 [   16    82]]
ROC-AUC: 0.9180771809286461


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
